engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: "phpmd.xml"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,lib"
      standard: "PSR1,PSR2"
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.php"
exclude_paths:
- tests/*